source('funcional/definitions.R')

p1 <- new_particle(new_point(10, 10), 20, new_point(0, 0), new_point(0, 0), 1024)
p2 <- new_particle(new_point(3, 3), 1, new_point(0, 0), new_point(0, 0), 0)
p3 <- new_particle(new_point(1, 1), 2, new_point(0, 0), new_point(0, 0), 0)
p4 <- new_particle(new_point(2, 2), 3, new_point(0, 0), new_point(0, 0), 0)
p5 <- new_particle(new_point(20, 20), 20, new_point(0, 0), new_point(0, 0), 256)

# messed up tree (p1 will be ignore on _toList bc root is an internal node)
root <- new_qnode(p1)
root[[2]] <- new_qnode(p2)
root[[3]] <- new_qnode(p3)
root[[4]] <- new_qnode(p4)
root[[5]] <- new_qnode(p5)

#print(root)
p_list = qnode_toList(root)
#print(p_list)

#quade = quad_from_input(p_list)
#print(quade)
#quade_center = quad_center(quade)
#print(quade_center)

#print(point_quadrant(particle_to_point(p1), quade_center))
#print(point_quadrant(particle_to_point(p2), quade_center))
#print(point_quadrant(particle_to_point(p3), quade_center))
#print(point_quadrant(particle_to_point(p4), quade_center))
#print(point_quadrant(particle_to_point(p5), quade_center))

#nroot = list()
#print(nroot)
#nroot = qnode_insert(nroot, quade, p1)
#print(nroot)
#quad_sub(quade, point_quadrant_i(particle_to_point(p1), quad_center(quade)))
#point_subquadrant(particle_to_point(p5), quade)
#nroot = qnode_append(nroot, 2, p1)
#nroot = qnode_insert(nroot, quade, p2)
#print(nroot)
#nroot = qnode_insert(nroot, quade, p5)
#print(nroot)
#nroot = qnode_insert(nroot, quade, p3)
#print(nroot)
#nroot = qnode_insert(nroot, quade, p4)
#print(nroot)

nroot = list_toQnode(qnode_toList(root))
#print(nroot)
#print(qnode_toList(nroot))